name: bimotew
# ------------------------------------ #
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
# ------------------------------------ #
jobs:
  meesot:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        testi: [179x.19, 2ud7, 278, 2v, 9e, 93h, os, yys,]
        flaga: [Aqhdw, hjjcis, ]
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: runneyr_go
      run: |
        sudo apt update -y && sleep 7
        
  roart-linux:
    needs: [meesot]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8,3.9]
        check: [tesv1,testv2,tesckt3,test 4,test5,test6,test7,test8,test9,test10]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Bauo maov .
      run: |
        cd testf
        ls
        pip3 install selenium
        python cimno.py
        
  roart-mac:
    needs: [meesot]
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8,3.9]
        check: [tes1,test2,test3,test4,test5,test6,test7,test8,test9,test10]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: EBromd mao ..
      run: |
        cd testf
        ls
        pip3 install selenium
        python cimno.py
